site_name: themarathoncoders
site_description: "Main documentation for themarathoncoders project"
repo_url: https://github.com/xgeeks-geekathon/themarathoncoders.git
edit_uri: edit/master/docs

# plugins:
#   - techdocs-core

# For sidebar navigation
nav:
  - Getting Started: "index.md"
